// Code generated by internal/protocolcontract/cmd/generate; DO NOT EDIT.
// Source: contracts/mimi-protocol/contract.json

import Foundation

enum MimiProtocolContract {
    static let schemaVersion = 1
    static let protocolName = "mimi-agent-api"
    static let currentRevision = 2
    static let minimumSupportedClientRevision = 1
    static let minimumSupportedServerRevision = 1
    static let legacyClientRevision = 1
    static let legacyServerRevision = 1
    static let clientRevisionHeader = "X-Mimi-Protocol-Revision"
    static let minimumServerRevisionHeader = "X-Mimi-Minimum-Server-Protocol-Revision"
    static let serverRevisionHeader = "X-Mimi-Server-Protocol-Revision"
    static let minimumClientRevisionHeader = "X-Mimi-Minimum-Client-Protocol-Revision"
    static let specSHA256 = "3256b2c6e44659390e71cd70036a4656f72fbfed9a74cd82bee3bd28c2438c0c"
    static let declaredCapabilities: Set<String> = [
        "codex_remote_full_access_v1",
        "file_upload_v1",
    ]

    /// REST 与 WebSocket 共用同一组握手 header，旧 agentd 会安全忽略未知 header。
    static func applyClientHeaders(to request: inout URLRequest) {
        request.setValue(String(currentRevision), forHTTPHeaderField: clientRevisionHeader)
        request.setValue(String(minimumSupportedServerRevision), forHTTPHeaderField: minimumServerRevisionHeader)
    }
}
