// Code generated by internal/protocolcontract/cmd/generate; DO NOT EDIT.
// Source: contracts/mimi-protocol/contract.json

package protocolcontract

const (
	SchemaVersion                  = 1
	ProtocolName                   = "mimi-agent-api"
	CurrentRevision                = 2
	MinimumSupportedClientRevision = 1
	MinimumSupportedServerRevision = 1
	LegacyClientRevision           = 1
	LegacyServerRevision           = 1
	ClientRevisionHeader           = "X-Mimi-Protocol-Revision"
	MinimumServerRevisionHeader    = "X-Mimi-Minimum-Server-Protocol-Revision"
	ServerRevisionHeader           = "X-Mimi-Server-Protocol-Revision"
	MinimumClientRevisionHeader    = "X-Mimi-Minimum-Client-Protocol-Revision"
	SpecSHA256                     = "3256b2c6e44659390e71cd70036a4656f72fbfed9a74cd82bee3bd28c2438c0c"
)

var currentCapabilities = []string{
	"codex_remote_full_access_v1",
	"file_upload_v1",
}

// Capabilities 返回副本，避免调用方修改进程级权威能力集合。
func Capabilities() []string {
	return append([]string(nil), currentCapabilities...)
}
